In [1]:
#Import the Library

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [4]:
#Import the Dataset

dataset = pd.read_csv('Churn-Modelling.csv')
X = dataset.iloc[ : ,3 :-1].values
Y = dataset.iloc[ : , -1].values
print(X)
print(Y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [5]:
#Encoding Categorical Data

#Level Encoding the “Gender” Column

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[ : , 2] = le.fit_transform(X[ : , 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
#On-Hot Encoding the “Geography” column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [7]:
#Use Sklearn to split user data into a training set and a testing set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)

In [8]:
#Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [10]:
#Adding the Input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

#Adding the second Hidden Layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

#Adding the Output Layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [17]:
#Training the ANN (Training + Compilation)

In [11]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [12]:
#Training the ANN on the Training Set
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6265 - loss: 0.6522
Epoch 2/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7916 - loss: 0.5005
Epoch 3/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8117 - loss: 0.4442
Epoch 4/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8121 - loss: 0.4355
Epoch 5/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8163 - loss: 0.4197
Epoch 6/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8252 - loss: 0.3982
Epoch 7/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8257 - loss: 0.3954
Epoch 8/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8155 - loss: 0.4167
Epoch 9/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8269 - loss: 0.3933
Epoch 10/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8275 - loss: 0.3923
Epoch 11/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8309 - loss: 0.3873
Epoch 12/100
219/219 ━━━━━━━━━━━━━━━━━━━━

In [13]:
#Making the predictions and Evaluating the Model

#Use the ANN model to predict if the customer with the following information will leave the bank:
#Geography: France
#Credit Score: 600
#Gender: Male
#Age: 40 Years old
#Tenure: 3 years
#Balance: 60000
#Number of Products: 2
#Does this customer have a credit card? : Yes
#Is this Customer an Active Member? : Yes
#Estimated Salary: 50000
#So, should we say goodbye to that customer?

#So, this ANN model predicts that this customer stays in the bank.

In [14]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]] )) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[False]]


In [15]:
#Predicting the Test Set Results

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1))

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [16]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[2273  106]
 [ 315  306]]


0.8596666666666667